import { ArrowRight, Building2, Camera, ClipboardCheck, FileCheck2, Gavel, Handshake, KeyRound, Landmark, MapPinned, Radio, ShieldCheck } from "lucide-react";
import Link from "next/link"; import { PageHero, Reveal, Shell } from "../components";
export const metadata={title:"SARFAESI Possession & Asset Security Services",description:"Authorised SARFAESI possession support, Section 14 DM/CMM coordination, police liaison, physical possession, secured property guarding, CCTV and legal documentation support.",alternates:{canonical:"/services"},openGraph:{title:"SARFAESI Possession and Asset Protection Services",description:"End-to-end operational support for banks, NBFCs, ARCs and authorised officers.",url:"/services",images:["/brand/pages/services-possession.png"]}};
const data = [
  [Gavel, "SARFAESI Possession Support", "Operational assistance to secured creditors and their authorised officers for possession of secured assets, strictly against applicable authority and instructions.", ["Pre-action file review", "Site reconnaissance", "Authorised field execution"]],
  [Landmark, "DM / CMM Process Coordination", "Administrative follow-up and field coordination around orders issued under Section 14, through the bank’s authorised officer and legal team.", ["Application tracking support", "Order coordination", "Officer liaison"]],
  [Handshake, "Police & Administration Liaison", "Advance coordination with the concerned police station, local administration and appointed officers for safe, orderly execution.", ["Police requisition follow-up", "Deployment scheduling", "Local coordination"]],
  [KeyRound, "Physical Possession Execution", "Controlled site access, occupant communication support, inventory, sealing and documented handover in the presence of authorised stakeholders.", ["Site control", "Inventory & panchnama support", "Sealing and handover"]],
  [ShieldCheck, "Asset Protection & Guarding", "Post-possession security cover to protect the asset against trespass, damage, theft and unauthorised re-entry.", ["24/7 guard deployment", "Visitor control", "Shift and incident reporting"]],
  [Camera, "Remote Monitoring", "CCTV, geotagged attendance, photographic site updates and escalation support for distributed secured-asset portfolios.", ["CCTV coordination", "Digital attendance", "Daily status reports"]],
  [FileCheck2, "Legal Documentation Support", "Operational document collation for panel advocates and authorised officers handling SARFAESI, recovery and possession matters.", ["Notice coordination", "Affidavit inputs", "Case-file tracking"]],
  [Building2, "Corporate Security", "Guarding and facility-support solutions for banks, offices, branches, warehouses and commercial premises.", ["Access management", "Patrol & surveillance", "Emergency response"]],
];
const process = [["01", "Mandate", "Receive the secured creditor’s written instruction and identify authorised stakeholders."], ["02", "Verify", "Review the possession order, asset schedule, address, boundaries and operational documents."], ["03", "Recon", "Assess access, occupancy, local sensitivities, manpower and safety requirements."], ["04", "Coordinate", "Align the bank, appointed officer, advocate, administration, police and security team."], ["05", "Execute", "Support controlled physical possession, inventory, photography, sealing and handover."], ["06", "Protect", "Deploy guards, activate reporting and maintain an auditable custody trail."]];
export default function Services() { return <Shell><PageHero kicker="BANKING & ASSET ENFORCEMENT" title={<>From mandate to<br /><em>secured possession.</em></>} copy="A coordinated operational layer for banks, NBFCs, ARCs, authorised officers and legal teams handling sensitive secured-asset assignments." /><section className="service-page section"><Reveal><p className="eyebrow dark"><i /> SPECIALIST SERVICES</p><h2 className="content-heading">Capability across the<br /><em>complete assignment.</em></h2></Reveal>{data.map(([I, t, p, items], i) => <Reveal className="service-row" key={t}><span>{String(i + 1).padStart(2, "0")}</span><I /><div><h2>{t}</h2><p>{p}</p></div><ul>{items.map(x => <li key={x}>{x}</li>)}</ul><Link href="/contact"><ArrowRight /></Link></Reveal>)}</section><section className="workflow section"><Reveal><p className="eyebrow"><i /> CONTROLLED WORKFLOW</p><h2>Six stages. One<br /><em>clear chain of custody.</em></h2></Reveal><div className="workflow-grid">{process.map(([n, t, p]) => <Reveal className="workflow-step" key={n}><b>{n}</b><h3>{t}</h3><p>{p}</p></Reveal>)}</div><p className="legal-note"><ClipboardCheck /> Services are performed only against valid written mandates and applicable orders. Statutory powers remain with the secured creditor, authorised officer and competent authority; FORCE009 provides authorised operational, coordination and security support.</p></section><section className="mini-cta"><h2>Plan your next possession assignment.</h2><Link className="button gold" href="/contact">Connect with operations <ArrowRight /></Link></section></Shell> }
