"use client";
import { useEffect, useRef, useState, Suspense } from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { Canvas, useFrame } from "@react-three/fiber";
import { Environment, Float, ContactShadows, Sparkles } from "@react-three/drei";
import * as THREE from "three";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { useGSAP } from "@gsap/react";
import Lenis from "lenis";
import { Menu, Phone, X } from "lucide-react";

gsap.registerPlugin(ScrollTrigger, useGSAP);
const links=[["Home","/"],["About","/about"],["Services","/services"],["Industries","/industries"],["Contact","/contact"]];

export function Brand(){return <Link className="brand" href="/" aria-label="FORCE009 The Facilitators — home"><img src="/brand/logo.png" alt="FORCE009 The Facilitators"/></Link>}
export function Shell({children}){const [open,setOpen]=useState(false);const path=usePathname();useEffect(()=>{const lenis=new Lenis({duration:1.05,smoothWheel:true});let id;const raf=t=>{lenis.raf(t);id=requestAnimationFrame(raf)};id=requestAnimationFrame(raf);return()=>{cancelAnimationFrame(id);lenis.destroy()}},[]);useGSAP(()=>{gsap.from("main",{opacity:0,duration:.55,ease:"power2.out"})},[path]);return <><header><Brand/><nav>{links.map(([n,h])=><Link className={path===h?"active":""} key={h} href={h}>{n}</Link>)}</nav><a className="call" href="tel:+917410809444"><Phone/> +91 74108 09444</a><button className="menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></header>{open&&<div className="mobile-menu">{links.map(([n,h])=><Link onClick={()=>setOpen(false)} key={h} href={h}>{n}</Link>)}</div>}<main>{children}</main><Footer/></>}
export function Footer(){return <footer><div className="footer-about"><Brand/><p>Authorised field coordination, secured-asset possession support and accountable post-possession protection for institutional clients.</p><span className="footer-badge">ACTIVE LLP · EST. 2016</span></div><div><b>COMPANY</b>{links.map(([n,h])=><Link key={h} href={h}>{n}</Link>)}</div><div><b>CORE SERVICES</b><Link href="/services">SARFAESI Support</Link><Link href="/services">Physical Possession</Link><Link href="/services">Administration Liaison</Link><Link href="/services">Asset Guarding</Link><Link href="/services">Corporate Security</Link></div><div><b>CONTACT & OFFICES</b><a href="tel:+917410809444">+91 74108 09444</a><a href="mailto:security.rajasthan@gmail.com">security.rajasthan@gmail.com</a><span>Jaipur: S-45, Subhash Nagar Shopping Centre, Bani Park, Jaipur 302016</span><span>Mumbai: 715, Mastermind V, Royal Palm Estate, Goregaon East 400065</span></div><div className="footer-legal"><span>© 2026 FORCE009 Security & Facilitators Network LLP</span><span>LLPIN AAH-3795 · Registered with RoC Mumbai</span><span>Services subject to valid mandate and applicable authority.</span></div></footer>}
export function Reveal({children,className=""}){const ref=useRef();useGSAP(()=>{gsap.from(ref.current,{y:45,opacity:0,duration:.9,ease:"power3.out",scrollTrigger:{trigger:ref.current,start:"top 88%"}})},{scope:ref});return <div ref={ref} className={className}>{children}</div>}
export function Magnetic({children}){const r=useRef();return <span ref={r} className="magnetic" onMouseMove={e=>{const b=r.current.getBoundingClientRect();gsap.to(r.current,{x:(e.clientX-b.left-b.width/2)*.16,y:(e.clientY-b.top-b.height/2)*.16,duration:.25})}} onMouseLeave={()=>gsap.to(r.current,{x:0,y:0})}>{children}</span>}
function Shield(){const group=useRef(),r1=useRef(),r2=useRef();useFrame((s,d)=>{group.current.rotation.y=THREE.MathUtils.lerp(group.current.rotation.y,s.pointer.x*.5,.04);group.current.rotation.x=THREE.MathUtils.lerp(group.current.rotation.x,-s.pointer.y*.24,.04);r1.current.rotation.z+=d*.18;r2.current.rotation.z-=d*.11});const shape=new THREE.Shape();shape.moveTo(0,2.4);shape.bezierCurveTo(1.8,2.05,2.25,1.85,2.2,.45);shape.bezierCurveTo(2.1,-1.45,.9,-2.45,0,-2.85);shape.bezierCurveTo(-.9,-2.45,-2.1,-1.45,-2.2,.45);shape.bezierCurveTo(-2.25,1.85,-1.8,2.05,0,2.4);return <group ref={group}><Float speed={2.4} rotationIntensity={.12} floatIntensity={.3}><mesh><extrudeGeometry args={[shape,{depth:.38,bevelEnabled:true,bevelSize:.13,bevelThickness:.13,bevelSegments:8}]}/><meshPhysicalMaterial color="#e49b22" metalness={.72} roughness={.18} clearcoat={1}/></mesh><mesh position={[0,0,.52]}><circleGeometry args={[.82,6]}/><meshStandardMaterial color="#512414" metalness={.55} roughness={.24}/></mesh><mesh position={[0,0,.56]}><torusGeometry args={[1.48,.022,10,140]}/><meshBasicMaterial color="#8d4cff"/></mesh></Float><group ref={r1}>{[0,1,2,3,4,5].map(i=><mesh key={i} position={[Math.cos(i*Math.PI/3)*3.1,Math.sin(i*Math.PI/3)*3.1,-.2]}><sphereGeometry args={[.1,20,20]}/><meshStandardMaterial color={i%2?"#10b8a3":"#6456e8"} emissive={i%2?"#10b8a3":"#6456e8"} emissiveIntensity={2}/></mesh>)}</group><mesh ref={r2} rotation={[1.18,0,.3]}><torusGeometry args={[3.2,.015,8,180]}/><meshBasicMaterial color="#11a995" transparent opacity={.55}/></mesh><Sparkles count={55} scale={[7,7,2]} size={2.2} speed={.25} color="#f2a51f"/></group>}
export function Scene(){return <Canvas camera={{position:[0,0,9],fov:40}} dpr={[1,1.8]} gl={{antialias:true,alpha:true}}><Suspense fallback={null}><ambientLight intensity={2.2}/><spotLight position={[4,6,7]} intensity={75} color="#ffd58a" angle={.38}/><pointLight position={[-4,1,5]} intensity={38} color="#725cff"/><pointLight position={[3,-3,4]} intensity={28} color="#0fc2ad"/><Shield/><ContactShadows position={[0,-3.2,0]} opacity={.18} scale={8} blur={3.5}/><Environment preset="studio"/></Suspense></Canvas>}
const pageVisuals={"ABOUT FORCE009":["/brand/pages/about-operations.png","FORCE009 operations leadership reviewing a secured property plan"],"BANKING & ASSET ENFORCEMENT":["/brand/pages/services-possession.png","Authorised team coordinating a secured commercial property handover"],"CLIENTS & ASSET CLASSES":["/brand/pages/industries-warehouse.png","Secured industrial warehouse with perimeter surveillance at blue hour"],"CONTACT":["/brand/pages/contact-command.png","FORCE009 operations coordinator handling an institutional assignment"]};
export function PageHero({kicker,title,copy}){const visual=pageVisuals[kicker];return <section className={`page-hero ${visual?"has-image":""}`}>{visual&&<img className="page-hero-image" src={visual[0]} alt={visual[1]}/>}<div className="page-hero-fade"/><div className="page-orbit"/><Reveal className="page-hero-copy"><p className="eyebrow"><i/>{kicker}</p><h1>{title}</h1><p>{copy}</p></Reveal>{visual&&<span className="page-hero-label">FORCE009 / FIELD OPERATIONS</span>}</section>}
